### ISSUE TITLE
请问 ubuntu 22.04 啥时候才能支持？

### ISSUE THREAD

**Issue by le45tx1m** [MoeClub/Note#25]
试过了光去掉注释好像没用，萌咖大佬啥时候更新一下呗

**Comment by leitbogioro** [comment]
更新：Ubuntu 22.04的安装通过中转AlpineLinux实现支持了，下载我增强版脚本，运行以下即可：

bash InstallNET.sh -ubuntu 22.04

Ubuntu 22.04 及以后版本或许以后再也不会支持了，简单来讲就是 Ubuntu 官方认为这种无人值守 preseed 网络安装方式性能太差，砍了。详情参见专栏文章：https://zhuanlan.zhihu.com/p/580612280 “附录”章，“探究不支持 Ubuntu 22.04 的原因”节。
Ubuntu 太能折腾人了，浪费时间在上面不值得，现在我的脚本支持 Debian 12，你可以试试。
下载：
wget --no-check-certificate -qO InstallNET.sh 'https://raw.githubusercontent.com/leitbogioro/Tools/master/Linux_reinstall/InstallNET.sh' && chmod a+x InstallNET.sh
安装 Debian 12：
bash InstallNET.sh -debian 12
